# Generated by Django 2.2.7 on 2020-01-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='idDone',
            field=models.BooleanField(default=False),
        ),
    ]
