# Generated by Django 2.2.7 on 2020-01-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0002_todo_iddone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='idDone',
            new_name='isDone',
        ),
    ]
